services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: push_notification
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - kafka
  kafka:
    image: bitnami/kafka:3.7
    container_name: kafka_notification
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
    volumes:
      - kafka_data:/bitnami/kafka

  mongo:
    image: mongo:6.0
    container_name: mongo_notification
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  kafka_data:
  mongo_data:
